### ISSUE TITLE
No module named 'notify2'

### ISSUE THREAD

**Issue by e-cesaroni** [jonian/acestream-launcher#11]
Hi, first of all, thanks for the fantastic repository. 
It used to work perfectly on my machine but now I'm getting the following error on Ubuntu 16.04:

`6f9fef81f4076
Traceback (most recent call last):
  File "/usr/bin/acestream-launcher", line 12, in <module>
    import notify2
ModuleNotFoundError: No module named 'notify2'
`

notify2 is installed on my machine, and I have tried to remove/reinstall the repository but it didn't solve the issue.

Many thanks,

**Comment by jonian** [comment]
Hi, yesterday I released version [1.0.0](https://github.com/jonian/acestream-launcher/releases/tag/v1.0.0) that does not use `python-notify2`. Can you try if it works?

**Comment by jonian** [comment]
I'm closing this since I tried it in ubuntu 16.04 and it works.
