### ISSUE TITLE
Syntax error: invalid syntax

### ISSUE THREAD

**Issue by dev-5k337** [jonian/acestream-launcher#12]
I am receiving the following error when attempting to use 'acestream-launcher'

Reproduce (on my machine) using:
`#: acestream-launcher acestream://<acestreamURLhere>`

**Error:**

> `stream-launcher acestream://b4d3f167b07dfd4d1421bc72a123456789123456`
> `File "/usr/bin/acestream-launcher", line 100`
> `subprocess.run(['notify-send', *args], **self.stdo)`
>  ` -------------------------------^                                `
> `SyntaxError: invalid syntax `

I am running:
``Linux Ubuntu 4.13.0-32-generic #35~16.04.1-Ubuntu SMP [2018 x86_64 x86_64 x86_64 GNU/Linux]``

_Ubuntu 16.04 (Xenial)_

**Comment by dev-5k337** [comment]
so...use python3?

**Comment by jonian** [comment]
@dev-5k337 No. Use latest version that fixes compatibility with python2.
