### ISSUE TITLE
acestreamengine not starting automatically

### ISSUE THREAD

**Issue by peledzius** [jonian/acestream-launcher#16]
When I'm trying to launch stream with ```acestream-launcher``` i'm getting message 
```
Stream unavailable!

Exiting...
```
But when I manually start ```acestreamengine --client-gtk``` or  ```acestreamengine --client-console``` then ```acestream-launcher``` works

**Comment by gi94** [comment]
It plays stream with mpv by default use:

    acestream-launcher “your url”

 If you want different player (vlc for exemple):

    acestream-launcher -p vlc “your url”

Regards.

**Comment by peledzius** [comment]
Sorry, but you didn't understood the problem here. By the way, I changed default player to VLC in ```acestream_launcher.py```.

**Comment by gi94** [comment]
On my computer, engine starts automatically

Be sure you have the latest version? (3.1.16-6)

**Comment by peledzius** [comment]
Yes, I installed ```acestream-launcher``` again, but problem persists.
```
acestreamengine --version
version: 3.1.16 revision: 3258
```
I'm on ```Xubuntu 16.04```

![problem](https://user-images.githubusercontent.com/24360494/39554223-42ec163a-4e7a-11e8-97a7-2bac327b2214.gif)

**Comment by jonian** [comment]
@gi94 Thank you for trying to help.
@peledzius I will have to set up a VM to test it. Any more info I should know to replicate your setup?

**Comment by peledzius** [comment]
@jonian I'm using not ```Ubuntu``` but ```Xubuntu 16.04 64bit```.
```
$ python -V
Python 2.7.12
```
```
$ curl -V
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```
```
$ dpkg -l | grep libnotify
ii  libnotify-bin                               0.7.6-2svn1                                                                 amd64        sends desktop notifications to a notification daemon (Utilities)
ii  libnotify4:amd64                            0.7.6-2svn1                                                                 amd64        sends desktop notifications to a notification daemon
ii  pidgin-libnotify                            0.14-9ubuntu2                                                               amd64        display notification bubbles in pidgin
```

**Comment by jonian** [comment]
@peledzius Try the master branch, it has a potential fix for this issue. Please report back if it works.

**Comment by peledzius** [comment]
@jonian Thank you, it works perfectly now.
