### ISSUE TITLE
passing options to engine

### ISSUE THREAD

**Issue by ghost** [jonian/acestream-launcher#18]
Hi,

I somehow doubt this is a bug (sorry if it isn't) I've been trying different ways to pass options to the engine but nothing seems to work.

> $ acestream-launcher 03ce2e15acf616aaf3cb94d64460993590095b30 -e --live-cache-type memory
>
> usage: acestream-launcher [-h] [-e ENGINE] [-p PLAYER] URL
acestream-launcher: error: argument -e/--engine: expected one argument

any idea what might be wrong?

**Comment by jonian** [comment]
Hi, the correct usage for the engine argument is:

```
acestream-launcher 03ce2e15acf616aaf3cb94d64460993590095b30 -e "acestreamengine --live-cache-type memory"
```
As the error says, the engine argument must be one.

**Comment by pstnta** [comment]
thanks, thing is, when I do it like that it just hangs.

> $ acestream-launcher 03ce2e15acf616aaf3cb94d64460993590095b30
LIVE - status: playing down: 660.0 kb/s up: 69.0 kb/s peers: 8


The above works, and loads instantly

> $ acestream-launcher 03ce2e15acf616aaf3cb94d64460993590095b30 -e "acestreamengine --live-cache-type memory"


this one just hangs and never loads, any idea?

**Comment by ghost** [comment]
thanks, thing is, when I do it like that it just hangs.

> $ acestream-launcher 03ce2e15acf616aaf3cb94d64460993590095b30
LIVE - status: playing down: 660.0 kb/s up: 69.0 kb/s peers: 8


The above works, and loads instantly

> $ acestream-launcher 03ce2e15acf616aaf3cb94d64460993590095b30 -e "acestreamengine --live-cache-type memory"


this one just hangs and never loads, any idea?

**Comment by jonian** [comment]
You should choose a client:
```
acestreamengine --client-console --live-cache-type memory
```

**Comment by ghost** [comment]
sorry man, another problem..

> $ acestream-launcher acestream://1270245b1c4198fcadd7f75a115f33589d725eaa -e "acestreamengine --client-console --live-cache-type memory"

>Streaming started, launching player...
>
> Exiting...
> LIVE - status: playing down: 0.0 kb/s up: 0.0 kb/s peers: 42
> $

It starts then crashes, player doesn't even open
