### ISSUE TITLE
Troubleshoot

### ISSUE THREAD

**Issue by swingcake** [jonian/acestream-launcher#19]
I just finished setting up acestream-launcher but getting an error,

```
gawd@tushbox:~$ acestream-launcher acestream://8e5f67a32e3df4c250d7481167e002110c47fde4
Acestream engine not found in provided path!

Exiting...
```

I did install all the dependencies and ran install.sh as root. Here is my /opt folder

![screenshot from 2018-06-15 12-47-22](https://user-images.githubusercontent.com/32037820/41455302-487e035a-709a-11e8-8571-1b0c83e5aa65.png)

I'm using Ubuntu 18.04. I followed [this](http://wiki.acestream.org/wiki/index.php/Install_Ubuntu) with http://dl.acestream.org/linux/acestream_3.1.16_ubuntu_16.04_x86_64.tar.gz

TIA

**Comment by thepante** [comment]
I had to use --engine even when wanted client-console. I run this:

> acestream-launcher --engine "acestreamplayer.engine --client-console" acestream://8e5f67a32e3df4c250d7481167e002110c47fde4

Working great. Using Ubuntu 18.04, acestream snap installed, 3.0.2-snap9

**Comment by swingcake** [comment]
@thepante But then you're using the acestream snap's engine, and not the acestream engine that I've installed viz, v3.1.16 from the acestream website.

**Comment by thepante** [comment]
@swingcake Following the link that you used, I get that maybe it will work as:
> acestream-launcher --engine "/opt/acestream/start-engine --client-console" acestream://8e5f67a32e3df4c250d7481167e002110c47fde4

Needless to say that this example is in case you had installed acestream with same path as the tutorial. Just point to the acestream installation and `/start-engine` with `--client-console` or `--client-gtk`

Remember that default the launcher is pointing to `acestreamengine --client-console` , but that isn't the command to launch it according to that link (neither with the snap)

**Comment by swingcake** [comment]
First of all, `acestream-launcher --engine "/opt/acestream/start-engine --client-console" URL` did not work.

Results in 
```
gawd@tushbox:~$ acestream-launcher --engine "/opt/acestream/start-engine --client-console" acestream://b419ca18726caafc046ca44a3f08382082c17e56
_
```
..and then I have to exit it.

Also I thought that 

> Remember that default the launcher is pointing to acestreamengine --client-console , but that isn't the command to launch it according to that link (neither with the snap)

was fixed with [if acestream engine is not in the system-path #1
](https://github.com/jonian/acestream-launcher/issues/1)

> Needless to say that this example is in case you had installed acestream with same path as the tutorial.

Yes, I've.
 
Any ideas what could work for me?

**Comment by thepante** [comment]
Maybe editing the .py ? open it with some editor: 

> sudo _gedit_ /opt/acestream-launcher/acestream_launcher.py

Line 32, where is 'default' edit it to your path to the start-engine

> default='/opt/acestream/start-engine --client-console'

Then should open as default: `acestream-launcher URL`
It worked in my case. Other things to check, is to be sure you have all the dependencies required for acestream and the launcher. Or try using the snap version - if you try it then use `/snap/acestreamplayer/7/opt/start-engine --client-console`

Note: Be sure the URL is working, I tried the one from the example in your results. The first time working great, but second to fifth time didn't work and it closed. Also opened other streams and worked with no problem.

![screenshot from 2018-06-16 10-44-41](https://user-images.githubusercontent.com/10443522/41499252-537da4fe-7153-11e8-9b9a-6ff564bbc791.png)

I have no more ideas at the moment 😅

**Comment by jonian** [comment]
@swingcake try with the engine from the repository (https://askubuntu.com/questions/763364/how-to-watch-acestream-sopcast-ubuntu-16-04-lts)

```
echo 'deb http://repo.acestream.org/ubuntu/ trusty main' | sudo tee /etc/apt/sources.list.d/acestream.list
sudo wget -O - http://repo.acestream.org/keys/acestream.public.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install acestream-engine
```

It should work without passing the engine argument.

**Comment by swingcake** [comment]
@jonian I think it is not functional as `http://repo.acestream.org/ubuntu/` gives me a 403 Forbidden error. 
Also, I've got the latest package by acestream, which is for 16.04. The one mentioned there is for trusty, 14.04.

That aside, I really hope so and think that I must be missing some dependency. But I do have python, curl, libnotify and ofcourse, the acestream engine. Also, mpv.

@thepante Can you try using the same engine as I'm (if you're also on Ubuntu 18.04)?
I'm struggling to get this to work!

I tried the snap, ran using `acestream-launcher --engine "acestreamplayer.engine --client-console" URL` and it worked. Still can't get it to run with the engine from acestream website v3.1.16.

**Comment by jonian** [comment]
I'm closing this since you found a solution (snap package) and it is not an acestream-launcher issue.

**Comment by user8873** [comment]
I'm sorry how to install it in a set with a player (http://wiki.acestream.org/wiki/index.php/Download - beta version, amd64: http://acestream.org/downloads/linux-beta/acestream_3.1.35_ubuntu_18.04_x86_64.tar.gz) on Linux Mint 19.1 Tessa, instructions are available in English, links, I'm a teapot.Or what is better?This has been going on for a week now, this is a big necessity, please.Thank.
