### ISSUE TITLE
Don't work in GUI mode on openSUSE Tumbleweed KDE

### ISSUE THREAD

**Issue by Drommer** [jonian/acestream-launcher#20]
I installed the package using the install.sh script. When starting from the console it works fine, but when you try to open a link from the browser or call the command with a link through the global search (Alt + F2), there are no notifications, you can see that acestreamengine has just started, then nothing happens.
System: openSUSE Tumbleweed KDE
AceStream Engine 3.1.16 (x64)
Browser: Firefox Nightly
Use "/opt/acestream-engine/start-engine --client-gtk" instead "acestreamengine --client-console".

P.S. Acestream Launcher is in the list of options, with which you can open links like "acestream://", after clicking on the "run" button, the launch icon appears on the taskbar for a few seconds.

**Comment by jonian** [comment]
Hi, do you have libnotify installed? Libnotify is used for the notifications using the `notify-send` command when calling acestream-launcher outside the terminal.

**Comment by Drommer** [comment]
@jonian now installed next package: python-notify python-notify-devel python2-notify2 python3-notify2 python3-pyinotify libnotify4 libnotify-tools libnotify-devel.

**Comment by jonian** [comment]
@Drommer So, does it work? Did you try to show a test notification with the `notify-send` command?

**Comment by Drommer** [comment]
@jonian Yes, this command works correctly, the notification is displayed. I also have installed sopcast-launcher, there are no problems with its work.

**Comment by jonian** [comment]
@Drommer Thanks.

**Comment by Drommer** [comment]
@jonian I'm not sure that you understood me correctly. The notify-send command works, but the acestream-launcher still does not work.

**Comment by jonian** [comment]
Ok. So any clue why it does not work? I do not use either OpenSUSE nor KDE. Does the `/opt/acestream-engine/start-engine --client-gtk` show an acestream icon in system tray? If not, install python2-libappindicator.

**Comment by Drommer** [comment]
@jonian I installed this OS recently. In the thematic chat of the system did not help me.
Yes, acestream-engine displays an icon in the tray, the python2-libappindicator package is not in this distribution, there is libappindicator1 and libappindicator3 and they are installed.

**Comment by Drommer** [comment]
@jonian

**Comment by Drommer** [comment]
@jonian I was able to run the script in graphical mode with output to the log and received next error:

Traceback (most recent call last):
  File "/usr/bin/acestream-launcher", line 277, in <module>
    launcher.run()
  File "/usr/bin/acestream-launcher", line 252, in run
    self.start_stream()
  File "/usr/bin/acestream-launcher", line 227, in start_stream
    self.notify('waiting')
  File "/usr/bin/acestream-launcher", line 96, in notify
    if not self.atty and self.notifier:
  File "/usr/bin/acestream-launcher", line 55, in notifier
    subprocess.run(['notify-send', '-v'], **self.stdo)
AttributeError: 'module' object has no attribute 'run'

Maybe this will help in solving the problem.

**Comment by Drommer** [comment]
@jonian the problem is solved by replacing "#!/usr/bin/env python" to "#!/usr/bin/python3".
P.S. I built a package for openSUSE: 
https://build.opensuse.org/package/show/home:drommer/acestream-launcher

**Comment by jonian** [comment]
@Drommer Thank you for finding the issue. Can I add your package for openSUSE, in the readme?

**Comment by Drommer** [comment]
@jonian Yes of course

**Comment by Drommer** [comment]
@jonian I moved "acestream-launcher" and "sopcast-launcher" packages for openSUSE to a separate repository: https://build.opensuse.org/project/show/home:drommer:p2pstreams. Please update links.

**Comment by jonian** [comment]
@Drommer Awesome! I didn't know you had a sopcast-launcher package. Thank you.

Is it possible to make this packages build for other distros? Also, do you know if there is a way to trigger builds when a new release is published on github?

Thanks again!

**Comment by Drommer** [comment]
@jonian On the build.opensuse.org site, you can build packages for many distros (Fedora, CentOS, Debian, etc). The packages that I built can theoretically work on Fedora and CentOS.

I can not say anything about the automatic update. I started building packages recently, I don’t know many nuances.

In my version, all package files are specified manually, therefore, with any changes, everything must be done anew.

P.S. Sorry for my English, I am not a native speaker, so I use a translator.
