### ISSUE TITLE
acestream-launcher function with last 32bit version?

### ISSUE THREAD

**Issue by penguin31** [jonian/acestream-launcher#22]
I arrived to install acestream engine 3.1.6 on MX Linux and Sparky Linux  64 bit.With acestream-engine running on background a started acestream-launcher to play ace streams. Works perfectly.The method is described here:
`https://forum.mxlinux.org/viewtopic.php?p=452024&sid=5e36d2b8336bb20940391d69c844798b#p452024`
I wanted also to install it on MX Linux 32 bit and Sparky Linux 32 bit. The latest acestream engine for Debian 32bit is version 3.0.2 and can be downloaded here:
`http://dl.acestream.org/debian/7/acestream_3.0.2_debian_7.6_i686.tar.gz`
or
`http://dl.acestream.org/ubuntu/14/acestream_3.0.3_ubuntu_14.04_i686.tar.gz`.
 I used the same method described for version 64 bit. Script file start_engine is missing on version 32 bit.Because I did not know how to start acestream engine,I copied it from 64 bit. Follow is Start_Engine,sh file
+++++++++++++++++++++++
#!/bin/sh
ROOT=$(readlink -f $(dirname $0))
LD_LIBRARY_PATH=${ROOT}/lib ${ROOT}/acestreamengine --lib-path $ROOT "$@"
++++++++++++++++++++++++
Some packages need to be installed also, as desrcibed here `https://aur.archlinux.org/packages/acestream-engine-i686/`

python-m2crypto
python-apsw
python3-apsw
python3-lxml
python3-setuptools
python-typing

I arrived to start acestream-engine with command:
/opt/acestrem/Start_engine acestreamengine --client-console --bind-all 
and with acestreamengine running on background, the next step :  

acestream-launcher acestream://b7a25312cd8bd517e2a5c3a97eee6b4d0ebef451
 (this stream is a functional stream on this moment), gives me this error :
Stream unavailable!

Exiting...
Is acestream-launcher valid for the version acestream-engine 32 bit (3.0.2)?

**Comment by jonian** [comment]
Hi, as it states in the readme:

> Since v1.0.0 acestream-launcher uses Acestream Engine HTTP API that is available on acestream-engine v3.1 or later.

So to make it work with acestream-engine 3.0.2 you should use the latest version before v1.0.0 from here https://github.com/jonian/acestream-launcher/archive/v0.5.0.zip.
