### ISSUE TITLE
Are download and upload speed limits working as intended?

### ISSUE THREAD

**Issue by ghost** [jonian/acestream-launcher#24]
Here is a streaming test I just took. As you can see download speed is way above the limit I used in my command. Am I doing this properly?

![image](https://user-images.githubusercontent.com/11262717/41932121-6d16a0de-7980-11e8-906b-e2d05c9aba70.png)

**Comment by jonian** [comment]
Yes, you are doing it properly. It seems like an issue with acestream-engine.
I'm closing this since acestream-launcher does not handle the download/upload limits.
