### ISSUE TITLE
Is is possible to output acestream to a playable video file ?

### ISSUE THREAD

**Issue by BurhanDanger** [jonian/acestream-launcher#26]
Is it possible to record the stream to play it later ?

**Comment by jonian** [comment]
Yes, use the player `-p` flag to give recording options or use the player interface to start recording.

**Comment by BurhanDanger** [comment]
Can you please give an example with ffmeg ?

**Comment by tp0** [comment]
I'm not sure about ffmpeg, you might have to pipe it, but mpv can do this too:

    acestream-launcher ID -p "mpv --record-file=filename.ts"

**Comment by bertzi87** [comment]
> Can you please give an example with ffmeg ?

acestream-launcher ID -v -p "ffmpeg -c copy filename.ts -i"
