### ISSUE TITLE
Does this work on MacOS? 

### ISSUE THREAD

**Issue by mahye82** [jonian/acestream-launcher#28]
I'd appreciate a clearer installation guide. How do I install the dependencies and what commands do I type into the terminal?

Which operating systems does this run on? I assume it's just Linux, but I want to be sure, since I haven't been able to find a good acestream solution for Mac.

**Comment by jonian** [comment]
Hi @mahye82. On Linux the installation is very easy:

- Install dependencies using your distribution package manager
- Run the `install.sh` script as root

I do not know if this will work on Mac-OS or Windows. Theoretically it should work on all operating systems that `python`, `curl`, and `acestream-engine` are supported.

I will leave this issue open in case someone, that knows how to install it on Mac-OS, can help you.

**Comment by DannyJJK** [comment]
`acestream-engine` isn't supported on macOS. For Mac I found that the best solution is to first install [Docker](https://docs.docker.com/v17.12/docker-for-mac/install/#download-docker-for-mac) then I used this script to run it through the IINA player https://github.com/n3d1117/acestream-iina/blob/master/play You can tweak the script to use another player or just get the streaming URL it generates. Not sure how technical you are but I could tweak that script to just display the streaming URL and then you just put it into your favorite media player
