### ISSUE TITLE
Doesn't start player if runs not in console 

### ISSUE THREAD

**Issue by qarkai** [jonian/acestream-launcher#29]
Engine never change self.live if stats not updated. They updated only if launcher started in tty.
When I start launcher as acestream protocol handler from browser there is no tty.
Change [this](https://github.com/jonian/acestream-launcher/blob/a2964ebad65d5cb76783963932da6928f3783746/acestream_engine.py#L182) to `while not self.is_live:` fixes issue.

**Comment by jonian** [comment]
Thank you for the report.
