### ISSUE TITLE
Not working on Updated Arch

### ISSUE THREAD

**Issue by joaojotta** [jonian/acestream-launcher#3]
So, here I am trying to use acestream and it stopped working in the past few days.
I'm on Arch (with Cinnamon) with everything up to date.
Here's the error:
```
Traceback (most recent call last):
  File "/usr/bin/acestream-launcher", line 12, in <module>
    import notify2
ModuleNotFoundError: No module named 'notify2'
```
Any tips?

**Comment by DylanSimowitz** [comment]
`pip install notify2` fixed it for me. You might have to run as root to get it to install.

**Comment by joaojotta** [comment]
`install: missing destination file operand after 'notify2'`

**Comment by jonian** [comment]
You have to rebuild python-notify2 from AUR. More info:

https://www.reddit.com/r/archlinux/comments/5mer2f/psa_rebuild_all_aur_packages_providing_python/

**Comment by joaojotta** [comment]
Thanks!
I was totally lost but finally managed to do it (not a Linux expert).
Thanks again!!
