### ISSUE TITLE
VLC is unable to open the MRL

### ISSUE THREAD

**Issue by nesttttt** [jonian/acestream-launcher#30]
Dear developers,

I receive the following error from VLC whenever I try to play a stream:

> Your input can't be opened:
> VLC is unable to open the MRL 'http://127.0.0.1:6878/ace/r/e45bd8ff300a36b01c90e7c1e1800d3cd284f694/d0b70def16a821fde6f2083994c7ea8e'. Check the log for details.

Here is the command that I used in this particular case:

> acestream-launcher "acestream://eda51c7f96e415583a311bc79771ad3974b4e809" -v -p vlc

Acestream-launcher claims no errors, and the log from VLC says the following:

> http error: failed to read answer
> access error: HTTP connection failure
> main error: read error: Operation now in progress
> http error: failed to read answer
> access error: HTTP connection failure
> http error: cannot connect to 127.0.0.1:6878

MPV works as desired, but it doesn't support chromecast.

Thank you in advance for your work.

**Comment by jonian** [comment]
Hi @nesttttt, thank you for your report. I checked the stream with VLC on Arch Linux and it works without problems. So, this might be a distro specific problem.

I will leave this issue open in case someone can help you. Please provide distro and VLC version info.

**Comment by nesttttt** [comment]
Thank you @jonian for your answer. I just updated VLC and now it works! Please excuse me for the inconvenience.

**Comment by jonian** [comment]
No inconvenience. Thanks for reporting.
