### ISSUE TITLE
Player doesn't show up

### ISSUE THREAD

**Issue by severoraz** [jonian/acestream-launcher#32]
I've been trying several streams but the player window never opens and there is no output on the console. How could I debug this?

I am running Arch Linux with Linux kernel 4.18.10-arch-1-ARCH x86_64.

**Comment by severoraz** [comment]
I'm closing this as I realized that the player won't show up until the "(pre-)buffering" status is completed, and the player moves to "playing" status.

**Comment by jonian** [comment]
@severoraz Happy you solved it. If you have any other problems, you can use `-v` argument to see the output from `acestream-engine` and the `player`:
```
-v, --verbose         Show engine and media player output in console
```
