### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by pemyunupa** [jonian/acestream-launcher#38]
Is it possible to set/change the ports acestreamengine uses?

**Comment by jonian** [comment]
I do not know if you can set/change the ports in acestreamengine, but you can use a docker container to achieve this:

```bash
docker run -p 8080:6878 -it pabsi/acestream-server
```

Now acestream-launcher has support for setting engine host and port in the [config file](https://github.com/jonian/acestream-launcher#configuration).
