### ISSUE TITLE
acestream-launcher: command not found

### ISSUE THREAD

**Issue by hutber** [jonian/acestream-launcher#40]
I have followed all of the instructions and download the latest versions from http://wiki.acestream.org/wiki/index.php/Install_Ubuntu

I noticed there was a `install.sh` file that I wonder if this defined the `acestream-launcher`?

```
hutber@hutber:/opt/acestream$ ll
total 36
drwxr-xr-x 4 hutber hutber  4096 Aug 11 14:46 ./
drwxr-xr-x 9 root   root    4096 Aug 11 14:20 ../
-rw-r--r-- 1 hutber hutber   250 Jul 15 14:53 acestream.conf
-rwxr-xr-x 1 hutber hutber 10224 Jul 15 14:29 acestreamengine*
drwxr-xr-x 6 hutber hutber  4096 Jul 15 14:53 data/
drwxr-xr-x 3 hutber hutber  4096 Jul 15 14:53 lib/
-rwxr-xr-x 1 hutber hutber   105 Aug 11 14:46 start-engine*

```

**Comment by jonian** [comment]
Install through pip https://github.com/jonian/acestream-launcher#installation

**Comment by hutber** [comment]
But pip is not longer supported :(

**Comment by hutber** [comment]
But pip is not longer supported.
Thanks
Jamie

**Comment by jonian** [comment]
Where is not supported? pypi.org shows instructions to install through pip https://pypi.org/project/acestream-launcher.

Has pip been replaced by another tool?

**Comment by jonian** [comment]
Also installation guide says to use pip https://packaging.python.org/tutorials/installing-packages/
