### ISSUE TITLE
Don't work with openssl-1.0-1.0.2.k-3

### ISSUE THREAD

**Issue by Haron-Prime** [jonian/acestream-launcher#5]
Acestream-launcher does not work with the new version openssl
`Acestream engine running.
xx Cannot load libraries: path /opt/acestream/lib
Traceback (most recent call last):
  File "<entry>", line 9, in <module>
  File "core.c", line 132, in 
ImportError: /usr/lib/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /opt/acestream/lib/acestreamengine/pycompat.so)
Error authenticating to Acestream!
Media Player not running...`
openssl-1.0-1.0.2.k-3
With version openssl-1.0-1.0.2.k-2 there are no problems

**Comment by Haron-Prime** [comment]
temporary workaround:
install libopenssl-1.0-compat and
`sudo ln -sf /usr/lib/libcrypto-compat.so.1.0.0 /opt/acestream/lib/libcrypto.so.1.0.0`
solves the problem, but... (((
It's a crutch

**Comment by jonian** [comment]
This is a bug in acestream engine package and I cannot do anything to fix it.
https://aur.archlinux.org/packages/acestream-engine/

Thanks for the workaround.
