### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by kuttarunge** [jonian/acestream-launcher#6]
when I try to use it I get:

ImportError: cannot import name __m2crypto
Error authenticating to Acestream!
Media Player not running...

**Comment by jonian** [comment]
If you are on arch you must downgrade python2-m2crypto to 0.23. This is an issue with acestream-engine package.

`pacman -U https://archive.archlinux.org/packages/p/python2-m2crypto/python2-m2crypto-0.23.0-2-x86_64.pkg.tar.xz`

https://aur.archlinux.org/packages/acestream-launcher
https://aur.archlinux.org/packages/acestream-engine

**Comment by kuttarunge** [comment]
its working, thanks for the help mate
