### ISSUE TITLE
smplayer will launch but never play any content

### ISSUE THREAD

**Issue by ghost** [jonian/acestream-launcher#9]
it starts to buffer but stays at 0%, vlc works fine same exact stream

**Comment by jonian** [comment]
Sorry, I do not use smplayer and I cannot help. This is not an acestream-launcher bug.

**Comment by tuxfusion** [comment]
For some reason you added -p <mediaplayer> which you never tested as you "don't use anything else" ? This test took me 3 minutes:

Broken:

acestream-launcher -p smplayer acestream://0edf47d20a684e362ec7b299f92389d6dd0b4292
acestream-launcher -p mplayer acestream://0edf47d20a684e362ec7b299f92389d6dd0b4292

Working:
acestream-launcher -p vlc acestream://0edf47d20a684e362ec7b299f92389d6dd0b4292
acestream-launcher -p mpv acestream://0edf47d20a684e362ec7b299f92389d6dd0b4292
acestream-launcher -p dragon acestream://0edf47d20a684e362ec7b299f92389d6dd0b4292
